FROM php:8.2-apache

# ติดตั้ง dependencies
RUN apt-get update && apt-get install -y \
        default-mysql-client \
        libzip-dev \
        unzip \
        libonig-dev \
        openssl \
        ca-certificates \
    && docker-php-ext-install pdo pdo_mysql mysqli \
    && a2enmod rewrite \
    && rm -rf /var/lib/apt/lists/*

# คัดลอกโค้ด PHP (Services)
COPY ./Services /var/www/html/

WORKDIR /var/www/html
EXPOSE 80
